language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: firebase
    project: dev
    skip_cleanup: true
    token:
      secure: fyrDWUNX8wfo6rOjFWL1+iNGvBsWKrHm3nv/5FzZMB/VNJHN/sKApVmLUnyntVA2stsSs+a49KX42vROlQbo5Em5x/Nm88vqLR3CKjFlE+3qtBCvsKMbNMHzojogdnAqv/QhBvHHWaCQTmQey4BY2eqSSC1HeaOcUqQqngcvXt3FDLIPArrTLGXlRtIgrIuzc4wYNSzd+xaJVXH3QqVT8mUu0AD+3AffdhZC/f2XIycB07Sve8dsKiiDjsi+5xKGeBqbaF92qT62JQmX1RBQ10o93AebiNgekt1CBPaCQNwIps+B9W+C46sqL99zwMYL3j8NedweOIVmcjZJyx9vmaeo7QGrVAoAMNtzmFyLED0ptGrqiNlJFkTWdoUTYLNdzU66wKPnVot8xhPoADX+G2T1zXQ/5aAehzuIBmQq9DRbkqUHc4XKDe+Kvqc1gKkg/7SCv18dzuAuvyfOXKgLq77EohfuSTh/5prJJiXWVMFPdDFxWzhWjQJX/IqJ1o44h6806wGB4I/8sU3WNP7UGfuHqzjsd22Zy0vDd1+kmtuvkpO0gFj++LAfOLMQxDYlnREhOzz8ART7+dSJv+y/7/4TvIuUEp5BpqptQ9+0De25Oa7zI8x3YQcizImK0UBfOImRmG1xR4xzHl8hN1NFPQURUorb2S9qK+Lt4VNSyYY=
    on:
      branch: develop
  - provider: firebase
    project: prod
    skip_cleanup: true
    token:
      secure: YLb1HHXsFYE8WLcm0KbmJ6S6jMjeMeeFKR9a1VxLeSbNfFkS/3dJItWAV8IhK4jojG9GLQ0pS5TSXDHmNEYvMrL460uT0JpNa5N1xpQVz2hUKc8c/Ay+uqu/4tnYR7hzZc2+zylCaridKVEWcdi5bIjZZwcRe+p3WW/o2qxE0tirHXTj7oG8qGJGdPcCs09tdPxiflLDzM0vTuFjSMYsKw8yZpkGJxGKLBvFnH4vd7XYgbVWY6bNHG8/4XMVPBrMoqpOf3dbymEN/H1YznyAagN3m4tS+ue0pelWjSXPX/cuXmJGWdJvIRUYTw5QIG9XJm1O/ZN4yy7lrZJEKw75sxr2/Xd1WCCANN60vL8nKbjZ0N+UnRM6VLs58MZzglqkmhkHfiTv2d5HwoYmQCGdnIw0/hNKDEUipibuI64DepM884/6hflOQt6SV+bvEwpP4axGitcF0He+4fhMvSaPEiTjigVNVkziI9UYqDQ+McRPP4rqcXyGHPKcgJchfcKuPSZeNPx5iXO2M2DMH078kMBFBN0LIJG4aTCBwaFkbMaohY7nBqaJwjipBLrbA4dYxhQ1GV1jQUEZ22BZHg8ULnCd6DNnUC40CcRVgpR1gGJUKXJfB8DXVdf4SGEDAOcGr+7PQ635fh2MSVihQshBZnIpla1lwzZ6HxJrzc6wdEc=
    on:
      branch: master
