language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: firebase
    project: dev
    skip_cleanup: true
    token:
      secure: fyrDWUNX8wfo6rOjFWL1+iNGvBsWKrHm3nv/5FzZMB/VNJHN/sKApVmLUnyntVA2stsSs+a49KX42vROlQbo5Em5x/Nm88vqLR3CKjFlE+3qtBCvsKMbNMHzojogdnAqv/QhBvHHWaCQTmQey4BY2eqSSC1HeaOcUqQqngcvXt3FDLIPArrTLGXlRtIgrIuzc4wYNSzd+xaJVXH3QqVT8mUu0AD+3AffdhZC/f2XIycB07Sve8dsKiiDjsi+5xKGeBqbaF92qT62JQmX1RBQ10o93AebiNgekt1CBPaCQNwIps+B9W+C46sqL99zwMYL3j8NedweOIVmcjZJyx9vmaeo7QGrVAoAMNtzmFyLED0ptGrqiNlJFkTWdoUTYLNdzU66wKPnVot8xhPoADX+G2T1zXQ/5aAehzuIBmQq9DRbkqUHc4XKDe+Kvqc1gKkg/7SCv18dzuAuvyfOXKgLq77EohfuSTh/5prJJiXWVMFPdDFxWzhWjQJX/IqJ1o44h6806wGB4I/8sU3WNP7UGfuHqzjsd22Zy0vDd1+kmtuvkpO0gFj++LAfOLMQxDYlnREhOzz8ART7+dSJv+y/7/4TvIuUEp5BpqptQ9+0De25Oa7zI8x3YQcizImK0UBfOImRmG1xR4xzHl8hN1NFPQURUorb2S9qK+Lt4VNSyYY=
    on:
      branch: develop
  - provider: firebase
    project: prod
    skip_cleanup: true
    token:
      secure: lWkC2H+QkR55uHD36dnsv4VafaESSHL90/SkAWu+Bi8OIWw8nHvuxXTR1gDzZd6aZWTxtRr2r4YP7C/82omCDtnrUFBTAfyDY07+WzT7yo2kpHF+14UfDUP6kmAJ0U83g4/6B0TEpw4SUveTPZ4sEG6JkVVj0iNCrokb3lHOAYR8dcxhHD8eoTjXMJg3/+UsBsov/rbMchMHUuPYAWqxJUV1duRBlsbGoilVhN6Dwbr7jh8hE+zVzMZmuVy+TRm7QSbKCf6fXSQMPrqdGCpY1+2wUjVMunVAtOmfQdFoOrcldhD+ir08z43SM23DMrSyeCYiha/xhsLb29Rta6QUgmgzH3AnIGGuQbYUzZPJoZtNbET6xMlU0lld2bBIMgpnPBQi4WGq7D151BS+d/Q7Kqla7QshWmzJEPEC59uiUIb0NCwJ6PxLa+0trLafpkFik1oV/8HL7+RsubcaKIGkfEK+LFe0RinlEwky1YL+CvENr8e7rPeprmZzvNEJ/xT7bWrKZwnsGt56jCSJEcgDvdTwdqS2HQ/9FgrQjiR6OH7EWOOcmo8GDsCaVif31wSS0DbyaYLCWIqgWwc0hRNZhkJdH3CuNpzoXP5wPhkF1yeVlzawY7ABb1kfo6WO9gxsca2FEX6u8YMQidhCWznKmOW3FGeraLcBNg5SsF9nyZw=
    on:
      branch: master
